### ISSUE TITLE
Change Request to Axios 

### ISSUE THREAD

**Issue by ephraimduncan** [sholomschonbuch/node.js#1]
I have seen that you are using request to make your API requests but request is deprecated, it is no longer maintained and you may face other issues in the coming future so I suggest you change it to any http client apart from request. Axios is better.

**Comment by sholomschonbuch** [comment]
Thank you so much for your help, I just started using learning JS, I have
more experience with python.
 I'm a beginner I was just wondering how you found my program?
 I'll try using Axios.
Thanks again if you see anything else it would be appreciated if you point
it out,
Sholom.

**Comment by ephraimduncan** [comment]
Thank you too and by the way, your code came up in a search.
